version: "3"

services:
  swagger:
    image: swaggerapi/swagger-editor
    restart: always
    ports:
      - ${SWAGGER_EDITOR_PORT}:8080

  swagger_ui:
    image: swaggerapi/swagger-ui
    restart: always
    volumes:
      - ./swagger.yml:/usr/share/nginx/html/swagger.yml
    environment:
      API_URL: ${SWAGGER_SPECIFICATION_URL}
    ports:
      - ${SWAGGER_UI_PORT}:8080
