openapi: 3.0.0
info:
  title: 業務支援システム
  description: "主な機能：\n   議事録の記録\n   スケジュール管理・共有\n   ファイル共有\n   チャット\n   Todo管理等"
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8080'
    description: 'OpenApi host'
paths:
  /user/current:
    get:
      tags:
        - user
      summary: 現在のユーザーを返す
      operationId: bf6ef126d7726fa13fdb0f3ef545f7cd
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: 'Unexpected Error'
          content:
            application/json:
              schema:
                properties:
                  message: { description: レスポンスパラメータの例を記載, type: string }
                type: object
components:
  schemas:
    user:
      description: ユーザー
      required:
        - id
        - full_name
        - created_at
        - updated_at
      properties:
        id:
          description: ユーザーID
          type: integer
        full_name:
          description: フルネーム
          type: string
          example: 'テスト 太郎'
        first_name:
          description: 名
          type: string
          example: 太郎
        last_name:
          description: 姓
          type: string
          example: テスト
        file_path:
          description: ファイルパス
          type: string
          example: users/test1.jpg
        created_at:
          description: 作成日時
          type: string
          format: datetime
          example: '2021-12-31 12:00:00'
        updated_at:
          description: 更新日時
          type: string
          format: datetime
          example: '2021-12-31 12:00:00'
      type: object
    User:
      title: User
      description: ユーザーのスキーマ
      required:
        - id
        - full_name
        - created_at
        - updated_at
      properties:
        id:
          description: ユーザID
          type: integer
          example: 1
        full_name:
          description: ユーザーフルネーム
          type: string
          example: 'テスト 太郎'
        first_name:
          description: 名
          type: string
          example: 太郎
        last_name:
          description: 姓
          type: string
          example: テスト
        file_path:
          description: 画像パス
          type: string
          example: user/user.jpg
        created_at:
          description: 作成日時
          type: string
          example: '2021-12-31 23:59:59'
        updated_at:
          description: 更新日時
          type: string
          example: '2021-12-31 23:59:59'
      type: object
tags:
  -
    name: user
    description: user
